name: root
channels:
  - pytorch
  - conda-forge
dependencies:
  - scipy
  - numpy<1.20
  - pandas>=0.21
  - jupyter
  - matplotlib
  - scikit-learn>=0.19,<0.22
  - seaborn
  - nilearn<0.8
  - keras
  - tensorflow
  - pytorch-cpu
  - torchvision-cpu
  - lightgbm
  - xgboost
  - catboost
  - statsmodels
  - joblib
  - networkx
  - tslearn
  - pip
  - pip:
      - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/0.2.1
      - https://api.github.com/repos/parisots/gcn/zipball/master
      - slidingwindow
