name: autism
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy<1.20
  - pandas>=0.21,<=1.1
  - jupyter
  - matplotlib<=3.2
  - scikit-learn>=0.19,<=0.21
  - seaborn
  - nilearn<=0.8
  - nibabel<=2.5
  - cloudpickle
  - pip
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/0.2.1
