name: autism
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy<1.20
  - pandas>=0.21,<1.2
  - jupyter
  - matplotlib<3.3
  - scikit-learn>=0.19,<0.22
  - seaborn
  - nilearn<0.9
  - nibabel<2.6
  - cloudpickle
  - pip
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/0.2.1
