name: autism
channels:
  - conda-forge
dependencies:
  - numpy<1.20
  - scipy
  - pandas>=0.21
  - scikit-learn>=0.19,<0.22
  - nilearn<0.8
  - matplotlib
  - seaborn
  - jupyter
  - cloudpickle
  - pip
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/0.2.1
